security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        movie_db:
            entity:
                class: App\Entity\User
                property: email
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false



        main:
            anonymous: true

            provider: movie_db

            form_login:
                login_path: login
                check_path: login
                default_target_path: home
                always_use_default_target_path: false
                use_referer: true

            logout:
                path: logout
                target: home


    # cette section va definir quel role on acces à quels page / lot de pages
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/film, roles: ROLE_USER }
        - { path: ^/category, roles: ROLE_USER }
         #l'expression reguliere indique "toute les urls qui commencent par /admin"
